name: Validate Brewfiles
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "custom/brew/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v5

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1ccc07ccd54b6048295516a3eb89b192c35057dc # master

      - name: Validate Brewfiles
        shell: bash
        run: bash build/validate-brewfiles.sh custom/brew
